### ISSUE TITLE
login.php

### ISSUE THREAD

**Issue by abaker94** [abaker94/prymal-esports-league#1]
### Tasks

- [ ]  Research other websites. Mainly > [MLG Website](https://gamebattles.majorleaguegaming.com/)
- [ ]  Create a database, be sure to include **EVERYTHING** that we may need.
- [ ]  Determine Style. _Be sure to make notes._
- [ ]  Coded correctly and to entirety.
